### ISSUE TITLE
Bad file descriptor for output file 

### ISSUE THREAD

**Issue by mario-kr** [anti-koerper/antikoerper#23]
Test run of antikoerper lead to this error message:
ERROR:antikoerper::app: Error creating file /home/----/antioutput/os.battery, Bad file descriptor (os error 9)

**Comment by TheNeikos** [comment]
can you also post your config so I can test locally?

**Comment by mario-kr** [comment]
[general]
shell = "/usr/bin/bash"

[[items]]
key = "os.battery"
interval = 6
command = "acpi"

program was called with:
./target/debug/antikoerper --config ./example_config.toml --output ~/antioutput -vvv

**Comment by TheNeikos** [comment]
Interesting... on my system it works, your fix in #24 is correct though, so I will just include that

**Comment by TheNeikos** [comment]
Fixed in #24
